LOCAL_PATH := device/sony/tetra

USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/sony/tetra/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_BOARD_PLATFORM := bcm_java
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT:= cortex-a7
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp

COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60 -DBINDER_COMPAT

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_BOOTLOADER_BOARD_NAME := tetra

# Display
BOARD_EGL_CFG := $(LOCAL_PATH)/configs/egl.cfg
TARGET_DISPLAY_USE_RETIRE_FENCE := true
TARGET_USES_C2D_COMPOSITION := true
TARGET_USES_ION := true
USE_OPENGL_RENDERER := true
OVERRIDE_RS_DRIVER := libRSDriver_adreno.so

# Kernel
BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive,hi=there
BOARD_KERNEL_BASE := 0x82000000
BOARD_KERNEL_PAGESIZE := 2048
#TARGET_KERNEL_SOURCE := kernel/sony/tetra
#TARGET_KERNEL_CONFIG := tetra_stock_defconfig
#cyanogenmod_tetra_defconfig
#TARGET_PREBUILT_KERNEL := device/sony/tetra/kernel
BOARD_KERNEL_IMAGE_NAME := zImage-dtb

BOARD_CANT_BUILD_RECOVERY_FROM_BOOT_PATCH := true

#BOARD_SEPOLICY_DIRS += \
#    device/sony/tetra/sepolicy

#BOARD_SEPOLICY_UNION += \
#    device/sony/tetra/sepolicy/file_contexts

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 23068672
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 23068672
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2873867264
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
BOARD_USE_CUSTOM_RECOVERY_FONT := \"font_7x16.h\"
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/config/recovery.fstab
